### ISSUE TITLE
Need feature to add region and endpoint 

### ISSUE THREAD

**Issue by mukro** [catalyst/moodle-local_aws#13]
I have my S3 bucket at ap-south-1 and endpoint apigateway.ap-south-1.amazonaws.com. Could you please make it configurable to add region and endpoint? The other option is to fetch these details from AWS API. WIth fixed list the plugin usage is limited to predefined regions.

**Comment by ewallah** [comment]
With the latest sdk (see https://github.com/catalyst/moodle-local_aws/pull/11) one can have  support for all current and future regions. 

```
$regions = [];
$all = require($CFG->dirroot . '/local/aws/sdk/Aws/data/endpoints.json.php');
$ends = $all['partitions'][0]['regions'];
if ($ends) {
    foreach ($ends as $key => $value) {
        $regions[$key] = $value['description'];
    }
}
$settings->add(,,,,$regions);
```

**Comment by brendanheywood** [comment]
+10

This should also define a admin setting that all the plugins can use directly
