### ISSUE TITLE
Dependency check  causes  warning in Moodle 3.5

### ISSUE THREAD

**Issue by collisiondetection** [catalyst/moodle-local_aws#14]
I have an activity plugin that requires another plugin to work correctly. I followed the recommendation 

of requesting this plugin as a dependency in the version.php file like this :

`$plugin->dependencies = array('local_aws' => 2017071501 ); //AWS php SDK  dependency

`
The problem is when I install my plugin I receive a Warning :

```
Warning: require_once(/var/www/moodle/local/aws/sdk/aws-autoloader.php): failed to open stream: 
No such file or directory in /var/www/moodle/mod/tutorship/lib.php on line 37
Fatal error: require_once(): Failed opening required '/var/www/moodle/local/aws/sdk/aws-autoloader.php' 
(include_path='/var/www/moodle/lib/pear:.:/usr/share/php') in /var/www/moodle/mod/mymodulep/lib.php on line 37
```
Line 37 uses this code:

```
// For AWS API Part
require_once($CFG->dirroot . '/local/aws/sdk/aws-autoloader.php');
```

So it seems to me during the install of my plugin the require_ once is not being satisfied as the AWS plugin has yet to be installed. Well I followed the recommendation of making it a dependency in version.php but it isn't being installed before the require_ once is checked ?
How can I resolve this conundrum ?

**Comment by brendanheywood** [comment]
Have you actually installed the local_aws plugin? Declaring dependencies doesn't install them for you. Also you code should not require that code during the install itself, only after it has been installed

**Comment by collisiondetection** [comment]
I didn't  install it  it.   I was under  the impression that  declaring a  dependency  plugin in version.php  would  install that  plugin. 

I don't  get  any  issues  if the   aws plugin is already installed.

**Comment by danmarsden** [comment]
As mentioned in the replies to your moodle.org forum post - the moodle installer isn't that clever. It just warns the admin that the plugin is required.

**Comment by collisiondetection** [comment]
Yes   looking  over  those  posts  on moodle.org forum  also  clarifies  the issue.
