### ISSUE TITLE
Can I remove folders / APIs  I am not using to reduce  size ? 

### ISSUE THREAD

**Issue by collisiondetection** [catalyst/moodle-local_aws#15]
I would  like to reduce the size  of  this plugin  so I can  bundle  it  within my own plugin.

Am I ok to  remove  some APIs /  folder  within SDK>AWS   ? 

Would  I need to change any   code  to make  it function  well. ?

**Comment by brendanheywood** [comment]
Those two things are mutually exclusive. If you want to bundle the AWS libs in your own plugin, then you will not install this plugin at all. This plugin should not change either way. 11M is really not that big, optimizing for disc usage for the code itself doesn't seem like much value compared to say terabytes of data disc usage. All the classes are auto loaded into memory on demand so there is no downside to php memory if you don't use certain bits of the api. I would recommend you just stick with declaring a dependency and not worry about it too much.
