### ISSUE TITLE
Objectfs does not implement a trashdir.

### ISSUE THREAD

**Issue by aspark21** [catalyst/moodle-local_aws#57]
Objectfs does not implement a trashdir.
line 995 of /admin/tool/objectfs/classes/local/store/object_file_system.php: call to debugging()
line 253 of /lib/filestorage/file_system_filedir.php: call to tool_objectfs\local\store\object_file_system->get_trash_fullpath_from_hash()
line 596 of /admin/tool/objectfs/classes/local/store/object_file_system.php: call to file_system_filedir->recover_file()
line 127 of /lib/filestorage/file_system_filedir.php: call to tool_objectfs\local\store\object_file_system->recover_file()
line 336 of /lib/filestorage/file_system.php: call to file_system_filedir->get_local_path_from_storedfile()
line 573 of /lib/filestorage/stored_file.php: call to file_system->add_storedfile_to_archive()
line 177 of /lib/filestorage/zip_packer.php: call to stored_file->archive_file()
line 144 of /lib/filestorage/zip_packer.php: call to zip_packer->archive_stored()
line 46 of /theme/norse/export.php: call to zip_packer->archive_to_pathname()

**Comment by danmarsden** [comment]
looks like a report related to the wrong plugin - maybe this should be reported to objectfs - not local_aws?
