### ISSUE TITLE
Undefined constant GuzzleHttp\Client::VERSION when creating a AwsClientTrait

### ISSUE THREAD

**Issue by ewallah** [catalyst/moodle-local_aws#65]
"Undefined constant GuzzleHttp\Client::VERSION" at
local/aws/sdk/GuzzleHttp/functions.php:136
local/aws/sdk/Aws/Handler/GuzzleV6/GuzzleHandler.php:40
local/aws/sdk/Aws/WrappedHttpHandler.php:88
local/aws/sdk/Aws/ClientSideMonitoring/AbstractMonitoringMiddleware.php:126
local/aws/sdk/Aws/S3/PermanentRedirectMiddleware.php:43
local/aws/sdk/Aws/S3/PutObjectUrlMiddleware.php:41
local/aws/sdk/Aws/Middleware.php:152
lib/guzzlehttp/promises/src/FulfilledPromise.php:41
lib/guzzlehttp/promises/src/TaskQueue.php:48
lib/guzzlehttp/promises/src/Promise.php:248
lib/guzzlehttp/promises/src/Promise.php:224
lib/guzzlehttp/promises/src/Promise.php:269
lib/guzzlehttp/promises/src/Promise.php:226
lib/guzzlehttp/promises/src/Promise.php:62
local/aws/sdk/Aws/AwsClientTrait.php:58
local/aws/sdk/Aws/AwsClientTrait.php:86

MOODLE version 4.2

**Comment by ewallah** [comment]
As a workaround, one can remove the Client::VERSION from the code or replace Client::VERSION with 1.1.

This workaround has only been tested when using AWS S3.
Before:
`$defaultAgent = 'GuzzleHttp/' . Client::VERSION;`
        
After:
`$defaultAgent = 'GuzzleHttp/';  or $defaultAgent = 'GuzzleHttp/1.1';`

**Comment by mark-webster-catalyst** [comment]
This is related to the fix in #56 accidentally being removed. There is a PR #64 to reinstate it.

**Comment by Frostist** [comment]
> As a workaround, one can remove the Client::VERSION from the code or replace Client::VERSION with 1.1.
> 
> This workaround has only been tested when using AWS S3. Before: `$defaultAgent = 'GuzzleHttp/' . Client::VERSION;`
> 
> After: `$defaultAgent = 'GuzzleHttp/'; or $defaultAgent = 'GuzzleHttp/1.1';`

Where does one find this in the code to change?

**Comment by Frostist** [comment]
> $defaultAgent = 'GuzzleHttp/'; or $defaultAgent = 'GuzzleHttp/1.1';

Amazing! this fix works perfectly for Moodle 4.3.2 as well. I did download the latest version of the AWS Moodle SDK but issue still seems to persist.

**Comment by marxjohnson** [comment]
This should be resolved now #58 is merged.
